# Generated by Django 5.2.17 on 2026-09-21 12:50

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ControlDiario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(unique=True)),
                ('observaciones', models.TextField(blank=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='controles_diarios_creados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'control_diario',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='ProductoControlDiario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('familia', models.CharField(blank=True, max_length=80)),
                ('sabor', models.CharField(blank=True, max_length=80)),
                ('presentacion', models.CharField(blank=True, max_length=80)),
                ('nombre', models.CharField(max_length=180, unique=True)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'producto_control_diario',
                'ordering': ['orden', 'nombre'],
                'indexes': [models.Index(fields=['activo'], name='idx_prod_ctrl_diario_activo')],
            },
        ),
        migrations.CreateModel(
            name='UbicacionControlDiario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=180, unique=True)),
                ('tipo', models.CharField(choices=[('PLANTA', 'Planta'), ('DEPOSITO', 'Depósito'), ('DISTRIBUIDOR', 'Distribuidor'), ('DESTINO', 'Destino'), ('OTRO', 'Otro')], default='OTRO', max_length=20)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'ubicacion_control_diario',
                'ordering': ['tipo', 'orden', 'nombre'],
                'indexes': [models.Index(fields=['tipo'], name='idx_ubic_ctrl_diario_tipo'), models.Index(fields=['activo'], name='idx_ubic_ctrl_diario_activo')],
            },
        ),
        migrations.CreateModel(
            name='MovimientoControlDiario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_movimiento', models.CharField(choices=[('DISPONIBLE', 'Disponible'), ('RESERVA', 'Reserva'), ('ASIGNACION', 'Asignación'), ('STOCK_DEPOSITO', 'Stock depósito'), ('DISTRIBUCION', 'Distribución'), ('PENDIENTE', 'Pendiente'), ('AJUSTE', 'Ajuste')], max_length=30)),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('observaciones', models.TextField(blank=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('control', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='control_diario.controldiario')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_control_diario', to='control_diario.productocontroldiario')),
                ('ubicacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_control_diario', to='control_diario.ubicacioncontroldiario')),
            ],
            options={
                'db_table': 'movimiento_control_diario',
                'ordering': ['control__fecha', 'tipo_movimiento', 'ubicacion__orden', 'producto__orden'],
            },
        ),
        migrations.AddIndex(
            model_name='controldiario',
            index=models.Index(fields=['fecha'], name='idx_control_diario_fecha'),
        ),
        migrations.AddIndex(
            model_name='movimientocontroldiario',
            index=models.Index(fields=['tipo_movimiento'], name='idx_mov_ctrl_diario_tipo'),
        ),
        migrations.AddIndex(
            model_name='movimientocontroldiario',
            index=models.Index(fields=['producto'], name='idx_mov_ctrl_diario_prod'),
        ),
        migrations.AddIndex(
            model_name='movimientocontroldiario',
            index=models.Index(fields=['ubicacion'], name='idx_mov_ctrl_diario_ubic'),
        ),
        migrations.AddConstraint(
            model_name='movimientocontroldiario',
            constraint=models.UniqueConstraint(fields=('control', 'producto', 'ubicacion', 'tipo_movimiento'), name='uniq_mov_control_prod_ubic_tipo'),
        ),
    ]
