"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.17.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

import environ


# ============================================================
# RUTAS BASE
# ============================================================

BASE_DIR = Path(__file__).resolve().parent.parent


# ============================================================
# VARIABLES DE ENTORNO
# ============================================================

env = environ.Env(
    DEBUG=(bool, False)
)

environ.Env.read_env(
    BASE_DIR / ".env"
)


# ============================================================
# GEMINI
# ============================================================

GEMINI_API_KEY = env(
    "GEMINI_API_KEY",
    default=""
)


# ============================================================
# SEGURIDAD GENERAL
# ============================================================

SECRET_KEY = env(
    "SECRET_KEY"
)

DEBUG = env.bool(
    "DEBUG"
)


ALLOWED_HOSTS = [
    "127.0.0.1",
    "localhost",
    "10.242.4.13",
]


# ============================================================
# APLICACIONES
# ============================================================

INSTALLED_APPS = [

    # Django
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",

    # Librerías
    "rest_framework",
    "corsheaders",

    # Talca
    "core",
    "maestros",
    "repartos",
    "rechazos",
    "cambios",
    "asistente",
    "planillas_recargas",
    "viaticos",
    "kilometrajes",
]


# ============================================================
# MIDDLEWARE
# ============================================================

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]


# ============================================================
# URLS / WSGI
# ============================================================

ROOT_URLCONF = "config.urls"


WSGI_APPLICATION = (
    "config.wsgi.application"
)


# ============================================================
# TEMPLATES
# ============================================================

TEMPLATES = [
    {
        "BACKEND":
            "django.template.backends.django.DjangoTemplates",

        "DIRS": [],

        "APP_DIRS": True,

        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]


# ============================================================
# BASE DE DATOS
# ============================================================

DATABASES = {
    "default":
        env.db(
            "DATABASE_URL"
        )
}


# Todo este sistema trabaja únicamente
# dentro del schema "log".
#
# NO tocar el schema "public".
DATABASES["default"]["OPTIONS"] = {
    "options":
        "-c search_path=log"
}


# ============================================================
# VALIDACIÓN DE CONTRASEÑAS
# ============================================================

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME":
            "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME":
            "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME":
            "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME":
            "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# ============================================================
# INTERNACIONALIZACIÓN
# ============================================================

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# ============================================================
# ARCHIVOS ESTÁTICOS
# ============================================================

STATIC_URL = "static/"


# ============================================================
# PRIMARY KEY POR DEFECTO
# ============================================================

DEFAULT_AUTO_FIELD = (
    "django.db.models.BigAutoField"
)


# ============================================================
# CORS
# ============================================================
#
# Permite que el frontend React se comunique con Django.
#
# Desarrollo:
#   http://localhost:5173
#   http://127.0.0.1:5173
#
# Producción Talca:
#   http://10.242.4.13:8001
#

CORS_ALLOWED_ORIGINS = [
    "http://localhost:5173",
    "http://127.0.0.1:5173",
    "http://10.242.4.13:8001",
]

CORS_ALLOW_CREDENTIALS = True


# ============================================================
# CSRF
# ============================================================
#
# Necesario porque usamos autenticación
# mediante sesiones de Django.
#

CSRF_TRUSTED_ORIGINS = [
    "http://localhost:5173",
    "http://127.0.0.1:5173",
    "http://10.242.4.13:8001",
]


# ============================================================
# SESIONES
# ============================================================
#
# La sesión permanece activa mientras
# el navegador esté abierto.
#
# Al cerrar completamente el navegador,
# la cookie de sesión debería expirar.
#

SESSION_EXPIRE_AT_BROWSER_CLOSE = True


# ============================================================
# EMAIL
# ============================================================

EMAIL_BACKEND = (
    "django.core.mail.backends.smtp.EmailBackend"
)

EMAIL_HOST = env(
    "EMAIL_HOST",
    default=""
)

EMAIL_PORT = env.int(
    "EMAIL_PORT",
    default=587
)

EMAIL_HOST_USER = env(
    "EMAIL_HOST_USER",
    default=""
)

EMAIL_HOST_PASSWORD = env(
    "EMAIL_HOST_PASSWORD",
    default=""
)

EMAIL_USE_TLS = env.bool(
    "EMAIL_USE_TLS",
    default=True
)

DEFAULT_FROM_EMAIL = env(
    "DEFAULT_FROM_EMAIL",
    default=EMAIL_HOST_USER,
)

RECIBOS_EMAIL_DESTINO = env(
    "RECIBOS_EMAIL_DESTINO",
    default="pasantes@talca.com.ar",
)


# ============================================================
# GOOGLE FORMS / RECHAZOS
# ============================================================

GOOGLE_RECHAZOS_URL = env(
    "GOOGLE_RECHAZOS_URL",
    default=""
)