# Generated by Django 5.2.17 on 2026-08-26 13:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('maestros', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReciboCambio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('pallets', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('pallets_observacion', models.TextField(blank=True)),
                ('pallets_descargados', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('pallets_descargados_observacion', models.TextField(blank=True)),
                ('prensados', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('prensados_observacion', models.TextField(blank=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('concesionario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recibos_cambio', to='maestros.concesionario')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recibos_cambio_creados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'recibo_cambio',
                'ordering': ['-fecha', '-id'],
            },
        ),
        migrations.CreateModel(
            name='DetalleReciboCambio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('observacion', models.TextField(blank=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('motivo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='detalles_cambio', to='maestros.motivocambio')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='detalles_cambio', to='maestros.producto')),
                ('recibo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='cambios.recibocambio')),
            ],
            options={
                'db_table': 'recibo_cambio_detalle',
                'ordering': ['recibo', 'producto__codigo'],
            },
        ),
        migrations.AddIndex(
            model_name='recibocambio',
            index=models.Index(fields=['fecha'], name='idx_recibo_cambio_fecha'),
        ),
        migrations.AddIndex(
            model_name='recibocambio',
            index=models.Index(fields=['concesionario'], name='idx_recibo_cambio_conc'),
        ),
        migrations.AddConstraint(
            model_name='recibocambio',
            constraint=models.UniqueConstraint(fields=('fecha', 'concesionario'), name='uq_recibo_fecha_concesionario'),
        ),
        migrations.AddConstraint(
            model_name='recibocambio',
            constraint=models.CheckConstraint(condition=models.Q(('pallets__gte', 0)), name='chk_recibo_pallets_no_neg'),
        ),
        migrations.AddConstraint(
            model_name='recibocambio',
            constraint=models.CheckConstraint(condition=models.Q(('pallets_descargados__gte', 0)), name='chk_recibo_pal_desc_no_neg'),
        ),
        migrations.AddConstraint(
            model_name='recibocambio',
            constraint=models.CheckConstraint(condition=models.Q(('prensados__gte', 0)), name='chk_recibo_prensados_no_neg'),
        ),
        migrations.AddIndex(
            model_name='detallerecibocambio',
            index=models.Index(fields=['recibo'], name='idx_detalle_cambio_recibo'),
        ),
        migrations.AddIndex(
            model_name='detallerecibocambio',
            index=models.Index(fields=['producto'], name='idx_detalle_cambio_prod'),
        ),
        migrations.AddIndex(
            model_name='detallerecibocambio',
            index=models.Index(fields=['motivo'], name='idx_detalle_cambio_motivo'),
        ),
        migrations.AddConstraint(
            model_name='detallerecibocambio',
            constraint=models.UniqueConstraint(fields=('recibo', 'producto'), name='uq_recibo_producto'),
        ),
        migrations.AddConstraint(
            model_name='detallerecibocambio',
            constraint=models.CheckConstraint(condition=models.Q(('cantidad__gte', 0)), name='chk_detalle_cambio_cant_no_neg'),
        ),
    ]
