# Generated by Django 5.2.17 on 2026-09-24 14:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('maestros', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Fletero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('apellido', models.CharField(blank=True, default='', max_length=120)),
                ('empresa', models.CharField(blank=True, default='', max_length=150)),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['nombre', 'apellido'],
            },
        ),
        migrations.CreateModel(
            name='OrdenCarga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=60, unique=True)),
                ('fecha', models.DateField()),
                ('estado', models.CharField(choices=[('RECIBIDA', 'Recibida'), ('CARGA_INICIADA', 'Carga iniciada'), ('PARCIAL', 'Parcial'), ('COMPLETA', 'Completa'), ('COMPLETA_CON_CAMBIO', 'Completa con cambio'), ('PENDIENTE_CONTROL', 'Pendiente de control')], default='RECIBIDA', max_length=30)),
                ('facturacion', models.CharField(choices=[('NO_APLICA', 'No aplica'), ('PENDIENTE_AVISO', 'Pendiente de aviso'), ('AVISADA', 'Avisada')], default='NO_APLICA', max_length=30)),
                ('observaciones', models.TextField(blank=True, default='')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordenes_expedicion_creadas', to=settings.AUTH_USER_MODEL)),
                ('fletero', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ordenes', to='expedicion.fletero')),
            ],
            options={
                'ordering': ['-fecha', '-id'],
            },
        ),
        migrations.CreateModel(
            name='MovimientoStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('INGRESO', 'Ingreso'), ('ORDEN_CARGA', 'Orden de carga'), ('AJUSTE', 'Ajuste'), ('REBOTE', 'Rebote'), ('DERRAME', 'Derrame'), ('CONSUMO_EMPLEADO', 'Consumo de empleado'), ('ANTICIPO_EMPLEADO', 'Anticipo de empleado')], max_length=30)),
                ('direccion', models.CharField(choices=[('ENTRADA', 'Entrada'), ('SALIDA', 'Salida')], max_length=10)),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=14)),
                ('referencia', models.CharField(blank=True, default='', max_length=120)),
                ('observaciones', models.TextField(blank=True, default='')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_stock_expedicion_creados', to=settings.AUTH_USER_MODEL)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_stock_expedicion', to='maestros.producto')),
                ('orden', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_stock', to='expedicion.ordencarga')),
            ],
            options={
                'ordering': ['-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='MovimientoMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referencia', models.CharField(blank=True, default='', max_length=120)),
                ('origen', models.CharField(blank=True, default='', max_length=120)),
                ('pallets_salida', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('pallets_entrada', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('chapadur_salida', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('chapadur_entrada', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_materiales_expedicion_creados', to=settings.AUTH_USER_MODEL)),
                ('fletero', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_materiales', to='expedicion.fletero')),
                ('orden', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_materiales', to='expedicion.ordencarga')),
            ],
            options={
                'ordering': ['-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='EntregaOrdenCarga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('inicio_carga', models.DateTimeField(blank=True, null=True)),
                ('fin_carga', models.DateTimeField(blank=True, null=True)),
                ('pallets_salida', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('pallets_entrada', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('chapadur_salida', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('chapadur_entrada', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('observaciones', models.TextField(blank=True, default='')),
                ('justificacion_stock', models.TextField(blank=True, default='')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entregas_expedicion_creadas', to=settings.AUTH_USER_MODEL)),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entregas', to='expedicion.ordencarga')),
            ],
        ),
        migrations.CreateModel(
            name='StockProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_unidades', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('stock_minimo', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('stock_critico', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('producto', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='stock_expedicion', to='maestros.producto')),
            ],
            options={
                'ordering': ['producto__codigo'],
            },
        ),
        migrations.CreateModel(
            name='DetalleEntregaOrdenCarga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_entregada', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entregas_expedicion', to='maestros.producto')),
                ('entrega', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='expedicion.entregaordencarga')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('entrega', 'producto'), name='unique_producto_entrega_expedicion')],
            },
        ),
        migrations.CreateModel(
            name='DetalleOrdenCarga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_solicitada', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='detalles_orden_expedicion', to='maestros.producto')),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='expedicion.ordencarga')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('orden', 'producto'), name='unique_producto_orden_expedicion')],
            },
        ),
    ]
