# Generated by Django 5.2.17 on 2026-09-10 12:53

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('maestros', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Viatico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_reparto', models.CharField(choices=[('LOCAL', 'Local'), ('LARGA_DISTANCIA', 'Larga distancia')], max_length=30)),
                ('fecha', models.DateField()),
                ('valor_viatico', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('cantidad_viaticos', models.PositiveIntegerField()),
                ('observaciones', models.TextField(blank=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('chofer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='viaticos', to='maestros.empleado')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='viaticos_creados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'viatico',
                'ordering': ['-fecha', '-id'],
                'indexes': [models.Index(fields=['fecha'], name='idx_viatico_fecha'), models.Index(fields=['tipo_reparto'], name='idx_viatico_tipo'), models.Index(fields=['chofer'], name='idx_viatico_chofer')],
            },
        ),
    ]
