# Generated by Django 5.2.17 on 2026-08-26 13:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('maestros', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reparto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('bultos', models.PositiveIntegerField(default=0)),
                ('puntos_venta', models.CharField(blank=True, max_length=50)),
                ('recargas', models.PositiveIntegerField(default=0)),
                ('observaciones', models.TextField(blank=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('asignacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='repartos', to='maestros.asignacion')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='repartos_creados', to=settings.AUTH_USER_MODEL)),
                ('vehiculo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='repartos', to='maestros.vehiculo')),
            ],
            options={
                'db_table': 'reparto',
                'ordering': ['-fecha', '-id'],
            },
        ),
        migrations.CreateModel(
            name='RepartoPersonal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(choices=[('CHOFER', 'Chofer'), ('AYUDANTE', 'Ayudante')], max_length=20)),
                ('orden', models.PositiveSmallIntegerField(default=0)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='participaciones_reparto', to='maestros.empleado')),
                ('reparto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personal', to='repartos.reparto')),
            ],
            options={
                'db_table': 'reparto_personal',
                'ordering': ['reparto', 'orden', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='reparto',
            index=models.Index(fields=['fecha'], name='idx_reparto_fecha'),
        ),
        migrations.AddIndex(
            model_name='reparto',
            index=models.Index(fields=['asignacion'], name='idx_reparto_asignacion'),
        ),
        migrations.AddIndex(
            model_name='reparto',
            index=models.Index(fields=['vehiculo'], name='idx_reparto_vehiculo'),
        ),
        migrations.AddIndex(
            model_name='repartopersonal',
            index=models.Index(fields=['reparto'], name='idx_reparto_personal_rep'),
        ),
        migrations.AddIndex(
            model_name='repartopersonal',
            index=models.Index(fields=['empleado'], name='idx_reparto_personal_emp'),
        ),
        migrations.AddConstraint(
            model_name='repartopersonal',
            constraint=models.UniqueConstraint(fields=('reparto', 'empleado'), name='uq_reparto_empleado'),
        ),
        migrations.AddConstraint(
            model_name='repartopersonal',
            constraint=models.UniqueConstraint(condition=models.Q(('rol', 'CHOFER')), fields=('reparto',), name='uq_reparto_un_chofer'),
        ),
    ]
