# Generated by Django 5.2.17 on 2026-09-11 11:46

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('maestros', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ControlKilometraje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_desde', models.DateField()),
                ('fecha_hasta', models.DateField()),
                ('observaciones', models.TextField(blank=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('chofer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='controles_kilometraje', to='maestros.empleado')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='controles_kilometraje_creados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'control_kilometraje',
                'ordering': ['-fecha_hasta', '-id'],
            },
        ),
        migrations.CreateModel(
            name='DestinoKilometraje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, unique=True)),
                ('distancia_km', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'destino_kilometraje',
                'ordering': ['nombre'],
                'indexes': [models.Index(fields=['activo'], name='idx_destino_km_activo')],
            },
        ),
        migrations.CreateModel(
            name='RegistroKilometraje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('cantidad_viajes', models.PositiveIntegerField(default=0)),
                ('distancia_km', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('observaciones', models.TextField(blank=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('control', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros', to='kilometrajes.controlkilometraje')),
                ('destino', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='registros_kilometraje', to='kilometrajes.destinokilometraje')),
            ],
            options={
                'db_table': 'registro_kilometraje',
                'ordering': ['fecha', 'destino__nombre'],
            },
        ),
        migrations.AddIndex(
            model_name='controlkilometraje',
            index=models.Index(fields=['chofer'], name='idx_control_km_chofer'),
        ),
        migrations.AddIndex(
            model_name='controlkilometraje',
            index=models.Index(fields=['fecha_desde', 'fecha_hasta'], name='idx_control_km_periodo'),
        ),
        migrations.AddConstraint(
            model_name='controlkilometraje',
            constraint=models.UniqueConstraint(fields=('chofer', 'fecha_desde', 'fecha_hasta'), name='uniq_control_km_chofer_periodo'),
        ),
        migrations.AddIndex(
            model_name='registrokilometraje',
            index=models.Index(fields=['fecha'], name='idx_registro_km_fecha'),
        ),
        migrations.AddIndex(
            model_name='registrokilometraje',
            index=models.Index(fields=['destino'], name='idx_registro_km_destino'),
        ),
        migrations.AddConstraint(
            model_name='registrokilometraje',
            constraint=models.UniqueConstraint(fields=('control', 'fecha', 'destino'), name='uniq_registro_km_control_fecha_dest'),
        ),
    ]
