# Generated by Django 5.2.17 on 2026-08-26 13:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('maestros', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Rechazo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('cliente', models.CharField(max_length=200)),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=12)),
                ('observaciones', models.TextField(blank=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('concesionario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rechazos', to='maestros.concesionario')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rechazos_creados', to=settings.AUTH_USER_MODEL)),
                ('motivo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rechazos', to='maestros.motivorechazo')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rechazos', to='maestros.producto')),
            ],
            options={
                'db_table': 'rechazo',
                'ordering': ['-fecha', '-id'],
                'indexes': [models.Index(fields=['fecha'], name='idx_rechazo_fecha'), models.Index(fields=['concesionario'], name='idx_rechazo_concesionario'), models.Index(fields=['producto'], name='idx_rechazo_producto'), models.Index(fields=['motivo'], name='idx_rechazo_motivo')],
            },
        ),
    ]
