# Generated by Django 5.2.17 on 2026-08-26 14:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maestros', '0001_initial'),
        ('rechazos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='rechazo',
            name='idx_rechazo_concesionario',
        ),
        migrations.RemoveIndex(
            model_name='rechazo',
            name='idx_rechazo_producto',
        ),
        migrations.RenameField(
            model_name='rechazo',
            old_name='observaciones',
            new_name='observacion',
        ),
        migrations.RemoveField(
            model_name='rechazo',
            name='cantidad',
        ),
        migrations.RemoveField(
            model_name='rechazo',
            name='cliente',
        ),
        migrations.RemoveField(
            model_name='rechazo',
            name='concesionario',
        ),
        migrations.RemoveField(
            model_name='rechazo',
            name='producto',
        ),
        migrations.AddField(
            model_name='rechazo',
            name='asignacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rechazos', to='maestros.asignacion'),
        ),
        migrations.AddField(
            model_name='rechazo',
            name='bultos',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rechazo',
            name='punto_venta',
            field=models.CharField(default='', max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rechazo',
            name='registrado_en',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='rechazo',
            index=models.Index(fields=['asignacion'], name='idx_rechazo_asignacion'),
        ),
    ]
