# Generated by Django 5.2.17 on 2026-09-07 14:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maestros', '0001_initial'),
        ('rechazos', '0002_remove_rechazo_idx_rechazo_concesionario_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='rechazo',
            name='origen',
            field=models.CharField(default='manual', max_length=30),
        ),
        migrations.AddField(
            model_name='rechazo',
            name='origen_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddIndex(
            model_name='rechazo',
            index=models.Index(fields=['origen'], name='idx_rechazo_origen'),
        ),
    ]
